repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings-file ./.isort.cfg .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: black
        name: black
        entry: black --config ./.black .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 --config .flake8 .
        language: system
        types: [ python ]
        pass_filenames: false
